package management.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CthdId generated by hbm2java
 */
@Embeddable
public class CthdId implements java.io.Serializable {

	private int sohd;
	private int mamh;

	public CthdId() {
	}

	public CthdId(int sohd, int mamh) {
		this.sohd = sohd;
		this.mamh = mamh;
	}

	@Column(name = "SOHD", nullable = false)
	public int getSohd() {
		return this.sohd;
	}

	public void setSohd(int sohd) {
		this.sohd = sohd;
	}

	@Column(name = "MAMH", nullable = false)
	public int getMamh() {
		return this.mamh;
	}

	public void setMamh(int mamh) {
		this.mamh = mamh;
	}

	
}
