package management.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * CtpdId generated by hbm2java
 */
@Embeddable
public class CtpdId implements java.io.Serializable {

	private int mapd;
	private int mamh;

	public CtpdId() {
	}

	public CtpdId(int mapd, int mamh) {
		this.mapd = mapd;
		this.mamh = mamh;
	}

	@Column(name = "MAPD", nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getMapd() {
		return this.mapd;
	}

	public void setMapd(int mapd) {
		this.mapd = mapd;
	}

	@Column(name = "MAMH", nullable = false)
	public int getMamh() {
		return this.mamh;
	}

	public void setMamh(int mamh) {
		this.mamh = mamh;
	}

	

}
