package management.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtpnId generated by hbm2java
 */
@Embeddable
public class CtpnId implements java.io.Serializable {

	private int mapn;
	private int mamh;

	public CtpnId() {
	}

	public CtpnId(int mapn, int mamh) {
		this.mapn = mapn;
		this.mamh = mamh;
	}

	@Column(name = "MAPN", nullable = false)
	public int getMapn() {
		return this.mapn;
	}

	public void setMapn(int mapn) {
		this.mapn = mapn;
	}

	@Column(name = "MAMH", nullable = false)
	public int getMamh() {
		return this.mamh;
	}

	public void setMamh(int mamh) {
		this.mamh = mamh;
	}

	

}
