package management.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Hoadon generated by hbm2java
 */
@Entity
@Table(name = "hoadon", uniqueConstraints = @UniqueConstraint(columnNames = "MAPD"))
public class Hoadon implements java.io.Serializable {

	private int sohd;
	private Khachhang khachhang;
	private Nhanvien nhanvien;
	private Phieudat phieudat;
	private Date ngayin;
	private Set<Cthd> cthds = new HashSet<Cthd>(0);

	public Hoadon() {
	}

	public Hoadon(int sohd, Nhanvien nhanvien) {
		this.sohd = sohd;
		this.nhanvien = nhanvien;
	}

	public Hoadon(int sohd, Khachhang khachhang, Nhanvien nhanvien, Phieudat phieudat, Date ngayin,
			Set<Cthd> cthds) {
		this.sohd = sohd;
		this.khachhang = khachhang;
		this.nhanvien = nhanvien;
		this.phieudat = phieudat;
		this.ngayin = ngayin;
		this.cthds = cthds;
	}

	@Id

	@Column(name = "SOHD", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getSohd() {
		return this.sohd;
	}

	public void setSohd(int sohd) {
		this.sohd = sohd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAKH")
	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANV", nullable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAPD", unique = true)
	public Phieudat getPhieudat() {
		return this.phieudat;
	}

	public void setPhieudat(Phieudat phieudat) {
		this.phieudat = phieudat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYIN", length = 10)
	public Date getNgayin() {
		return this.ngayin;
	}

	public void setNgayin(Date ngayin) {
		this.ngayin = ngayin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadon")
	public Set<Cthd> getCthds() {
		return this.cthds;
	}

	public void setCthds(Set<Cthd> cthds) {
		this.cthds = cthds;
	}

}
