package management.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mathang generated by hbm2java
 */
@Entity
@Table(name = "mathang")
public class Mathang implements java.io.Serializable {

	
	private String mamh;
	
	private Chatlieu chatlieu;
	
	private Loaimh loaimh;
	private Nhanhieu nhanhieu;
	private String tenmh;
	private String mota;
	private int trangthai;
	private Integer cachlam;
	private String slug;
	
	private Set<Hinhanhmh> hinhanhmhs = new HashSet<Hinhanhmh>(0);
	private Set<Banggia> banggias = new HashSet<Banggia>(0);
	private Set<Ctpn> ctpns = new HashSet<Ctpn>(0);
	private Set<Cthd> cthds = new HashSet<Cthd>(0);
	private Set<Ctddh> ctddhs = new HashSet<Ctddh>(0);
	private Set<Ctdkm> ctdkms = new HashSet<Ctdkm>(0);
	private Set<Ctpd> ctpds = new HashSet<Ctpd>(0);
	private Set<Ctsize> ctsizes = new HashSet<Ctsize>(0);
	
	private Set<Danhgia> danhgias = new HashSet<Danhgia>(0);
    private String nhan;
	public Mathang() {
	}
   
	public Mathang(String mamh, Nhanhieu nhanhieu, String tenmh, String mota, int trangthai,String nhan) {
		this.mamh = mamh;
		this.nhanhieu = nhanhieu;
		this.tenmh = tenmh;
		this.mota = mota;
		this.trangthai = trangthai;
		this.nhan=nhan;
	}
	public Mathang(String mamh,String tenmh) {
		this.mamh = mamh;
		this.tenmh = tenmh;
	}
	public Mathang(String mamh, Chatlieu chatlieu, Loaimh loaimh, Nhanhieu nhanhieu, String tenmh,
			String mota, int trangthai, Integer cachlam, Set<Hinhanhmh> hinhanhmhs,
			Set<Banggia> banggias, Set<Ctpn> ctpns, Set<Cthd> cthds, Set<Ctddh> ctddhs,Set<Ctsize> ctsizes, Set<Ctdkm> ctdkms,
			Set<Ctpd> ctpds, Set<Danhgia> danhgias) {
		this.mamh = mamh;
		this.chatlieu = chatlieu;
		
		this.loaimh = loaimh;
		this.nhanhieu = nhanhieu;
		this.tenmh = tenmh;
		this.mota = mota;
		this.trangthai = trangthai;
		this.cachlam = cachlam;
		
		this.hinhanhmhs = hinhanhmhs;
		this.banggias = banggias;
		this.ctpns = ctpns;
		this.cthds = cthds;
		this.ctddhs = ctddhs;
		this.ctdkms = ctdkms;
		this.ctpds = ctpds;
		this.ctsizes = ctsizes;
		
		this.danhgias = danhgias;
		
	}

	@Id

	@Column(name = "MAMH", unique = true, nullable = false, length = 10)
	public String getMamh() {
		return this.mamh;
	}

	public void setMamh(String mamh) {
		this.mamh = mamh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MACL")
	public Chatlieu getChatlieu() {
		return this.chatlieu;
	}

	public void setChatlieu(Chatlieu chatlieu) {
		this.chatlieu = chatlieu;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MALOAIMH")
	public Loaimh getLoaimh() {
		return this.loaimh;
	}

	public void setLoaimh(Loaimh loaimh) {
		this.loaimh = loaimh;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MANH", nullable = true)
	public Nhanhieu getNhanhieu() {
		return this.nhanhieu;
	}

	public void setNhanhieu(Nhanhieu nhanhieu) {
		this.nhanhieu = nhanhieu;
	}

	@Column(name = "TENMH", nullable = false, columnDefinition = "nvarchar(500)")
	public String getTenmh() {
		return this.tenmh;
	}
	public void setTenmh(String tenmh) {
		this.tenmh = tenmh;
	}
	@Column(name = "SLUG", nullable = false, columnDefinition = "varchar(500)")
	
	public String getSlug() {
		return slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}


	
	@Column(name = "NHAN", nullable = true)
	public String getNhan() {
		return nhan;
	}

	
	public void setNhan(String nhan) {
		this.nhan = nhan;
	}
	@Column(name = "MOTA", nullable = true, columnDefinition = "nvarchar(3000)")
	public String getMota() {
		return this.mota;
	}

	

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "TRANGTHAI", nullable = true)
	public int getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(int trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "CACHLAM")
	public Integer getCachlam() {
		return this.cachlam;
	}

	public void setCachlam(Integer cachlam) {
		this.cachlam = cachlam;
	}

	

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Hinhanhmh> getHinhanhmhs() {
		return this.hinhanhmhs;
	}

	public void setHinhanhmhs(Set<Hinhanhmh> hinhanhmhs) {
		this.hinhanhmhs = hinhanhmhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Banggia> getBanggias() {
		return this.banggias;
	}

	public void setBanggias(Set<Banggia> banggias) {
		this.banggias = banggias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctpn> getCtpns() {
		return this.ctpns;
	}
	
	public void setCtpns(Set<Ctpn> ctpns) {
		this.ctpns = ctpns;
	}
	///--------
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	
	public Set<Ctsize> getCtsizes() {
		return ctsizes;
	}

	public void setCtsizes(Set<Ctsize> ctsizes) {
		this.ctsizes = ctsizes;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Cthd> getCthds() {
		return this.cthds;
	}



	public void setCthds(Set<Cthd> cthds) {
		this.cthds = cthds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctddh> getCtddhs() {
		return this.ctddhs;
	}

	public void setCtddhs(Set<Ctddh> ctddhs) {
		this.ctddhs = ctddhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctdkm> getCtdkms() {
		return this.ctdkms;
	}

	public void setCtdkms(Set<Ctdkm> ctdkms) {
		this.ctdkms = ctdkms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Ctpd> getCtpds() {
		return this.ctpds;
	}

	public void setCtpds(Set<Ctpd> ctpds) {
		this.ctpds = ctpds;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mathang")
	public Set<Danhgia> getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set<Danhgia> danhgias) {
		this.danhgias = danhgias;
	}

}
